vich_uploader:
    db_driver: orm
    mappings:
        resource_images:
            uri_prefix: '%app.resource.images%'
            upload_destination: '%kernel.project_dir%/public%app.resource.images%'
